<?php
/**
 * @file
 * A description of what your module does.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_presave().
 */
function hir_rest_resources_entity_presave(EntityInterface $entity)
{
    if ($entity instanceof NodeInterface and $entity->bundle() == 'advert') {
        $couchDbService = Drupal::service('hir_rest_resources.couchdb_service');
        $normalized = $couchDbService->normalizeEntity($entity);
        if ($entity->isNew()) {
            $result = $couchDbService->createEntity($normalized);
            $entity->set('field_advert_couch_id', $result[0]);
            $entity->set('field_advert_couch_rev', $result[1]);
        } else {
            $couch_id = $entity->get('field_advert_couch_id')->value;
            $couch_rev = $entity->get('field_advert_couch_rev')->value;
            if (isset($couch_id)) {
                $result = $couchDbService->updateEntity($normalized, $couch_id, $couch_rev);
                $entity->set('field_advert_couch_rev', $result[1]);
            } else {
                $result = $couchDbService->createEntity($normalized);
                $entity->set('field_advert_couch_id', $result[0]);
                $entity->set('field_advert_couch_rev', $result[1]);
            }
        }
    }
}