<?php
/**
 * @file
 * A description of what your module does.
 */

use Doctrine\CouchDB\CouchDBClient;
use Doctrine\CouchDB\HTTP\HTTPException as HTTPExceptionAlias;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\TypedData\Exception\MissingDataException;
use Drupal\hir_rest_resources\Normalizer\TypedDataNormalizer;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_update().
 */
function hir_rest_resources_entity_update(EntityInterface $entity)
{
    Drupal::logger('hir_rest_resources')->info($entity->bundle());
    if ($entity instanceof NodeInterface and $entity->bundle() == 'advert') {
        $client = CouchDBClient::create(array('dbname' => 'hir'));
        try {
            $normalized = (new TypedDataNormalizer())->normalize($entity->getTypedData()->toArray(), null, array());
            $client->postDocument($normalized);
        } catch (HTTPExceptionAlias $e) {
            Drupal::logger('hir_rest_resources')->error(json_encode($e));
        } catch (MissingDataException $e) {
        }
    }
}